#!/usr/bin/env bash
# Installs and setup haproxy

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.4
sudo apt-get -y update
sudo apt-get install -y haproxy

sudo echo "ENABLED=1" > /etc/default/haproxy

# Listen to web1 and web2 servers                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
sudo echo "
listen load_balancer
bind *:80
mode http
balance roundrobin
option httpclose
option forwardfor
server 405511-web-01 54.157.165.55:80 check
server 405511-web-02 18.207.142.172:80 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy start
